version: "3.7"
services:
  adminer:
    image: adminer:4
    ports:
      - "18080:8080"
    restart: on-failure
  postgres:
    image: postgres:10-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./keycloak_poc.sql
        target: /docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data:
